### ISSUE TITLE
LOJ-1016 Brush (II) Easy Solution

### ISSUE THREAD

**Issue by Md-Kais** [lightoj-dev/problem-tutorials#334]
I have a tutorial. 
I think,  lower_bound  and unique stl and vector is enough for this problem.
At first, we take all the y-axis in our vector, and then make it unique by using unique stl.
Then, all we have to do to find where the next moving point starts.
so, I decided to using lower_bound to find this answer.
```
 auto low=lower_bound(point.begin(),point.end(),point[i]+w+1);
```
and then increase the iterator  to this value. and every iteration we increase the answer.

```
#include<bits/stdc++.h>
using namespace std;
#define optimize() ios_base::sync_with_stdio(0);cin.tie(0);cout.tie(0);
#define test int t;cin>>t;while(t--)
int main(){
    
    int T=1;
    optimize();

    test{
        vector<int>point;
        int n,w;
        cin>>n>>w;
        for(int i=0;i<n;i++){
            int x,y;cin>>x>>y;
            point.push_back(y);
        }

        sort(point.begin(),point.end());
        auto ip=unique(point.begin(),point.end());
        point.resize(distance(point.begin(),ip));
        int ans=0;
        for(int i=0;i<point.size();){
            //cout << point[i] << "point" << endl;
            ans++;
            auto low=lower_bound(point.begin(),point.end(),point[i]+w+1);
            i = low - point.begin();
            ///cout<<i<<endl;
            
        }
        cout<<"Case "<<T<<": "<<ans<<endl;
        T++;

    }
return 0;
}
  
```

**Comment by showrav-ansary** [comment]
@Md-Kais Hello dear! You are absolutely right about that. I too have admitted in the editorial that manual sorting was a matter of choice as long as we sort the coordinates in any preference. Using sets can solve the problem too as I have already stated that any DS that takes input in a sorted manner will work great. The core principle of yours and mine are the same. As you too can see, our time complexity and memory complexity is the same. But feel free to write down a `simplified implementation` ❤️ I have put the raw quick sort so that even beginners can grasp that the core principle of the problem is simply just to sort -> check range -> update range.

**Comment by faiyaz26** [comment]
@Md-Kais feel free to update this tutorial https://github.com/lightoj-dev/problem-tutorials/blob/main/1016/en.md with your solution and explanation.
