### ISSUE TITLE
1080 - Binary Simulation

### ISSUE THREAD

**Issue by ar-pavel** [lightoj-dev/problem-tutorials#67]

**Comment by rebornplusplus** [comment]
Hello, are you still working on this?

**Comment by ar-pavel** [comment]
yeah, I will try to make a pull request tomorrow

**Comment by rebornplusplus** [comment]
Hello, great effort! :1st_place_medal: 

I have some confusions in some of the parts. Let's discuss them.

 >Fact: as the input string is consist of only 0 and 1, and the type of update is only inverting the index, no matter how many inversions you make it will be same in each odd inversion count and vise versa, 1 will remain 1 after 1,3,5,.. inversions and will become 0 after 2,4,6,.. inversions, for example.

* Shouldn't this be "1 will remain 1 after 2,4, 6.. inversions and will be 0 otherwise"?

* In the image for `query(I, 5, 5)`, shouldn't the node value for `2-4` be 0 instead of 1 since the update is only to the right subtree of `1-7`?

* You mentioned lazy propagation for `invertRange`, but I don't see any propagation in your code. Rather, you are calculating the sum of the values of ancestor nodes for a particular point modulo 2.
